// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_PROJECT_ID = 'rdwuqmrjlknvtohzicqe';
const DEFAULT_SUPABASE_URL = `https://${DEFAULT_SUPABASE_PROJECT_ID}.supabase.co`;
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd3VxbXJqbGtudnRvaHppY3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMTU4MjEsImV4cCI6MjA4Njc5MTgyMX0.sA3FXuSf9yitwOBXAbv2uJs5aVaUYsv3LV-CZ5jB2VE';

const env = import.meta.env as Record<string, string | undefined>;
const projectId = env.VITE_SUPABASE_PROJECT_ID?.trim() || DEFAULT_SUPABASE_PROJECT_ID;
const derivedUrl = `https://${projectId}.supabase.co`;

const SUPABASE_URL =
  env.VITE_SUPABASE_URL?.trim() ||
  env.NEXT_PUBLIC_SUPABASE_URL?.trim() ||
  env.SUPABASE_URL?.trim() ||
  derivedUrl ||
  DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ||
  env.VITE_SUPABASE_ANON_KEY?.trim() ||
  env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() ||
  env.SUPABASE_PUBLISHABLE_KEY?.trim() ||
  env.SUPABASE_ANON_KEY?.trim() ||
  DEFAULT_SUPABASE_PUBLISHABLE_KEY;
const MISSING_CONFIG_MESSAGE =
  'Missing Supabase config. Set VITE_SUPABASE_URL (or VITE_SUPABASE_PROJECT_ID) and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).';

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error(MISSING_CONFIG_MESSAGE);
}

// Keep app booting even when config is missing, so UI can show actionable errors.
const SAFE_SUPABASE_URL = SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SAFE_SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SAFE_SUPABASE_URL, SAFE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
